name: xgb_snv_ga_feature_selection
description: XGBoost regression with SNV transformation and Genetic Algorithm feature selection for Brix prediction

# Data configuration
data:
  data_path: data/raw/Tomato_Viavi_Brix_model_pulp.csv
  target_column: Brix
  transform: snv
  savgol:
    enabled: true
    window_length: 11
    polyorder: 2
    deriv: 2
  remove_outliers: true

# Feature selection configuration
feature_selection:
  method: ga
  n_features: 25
  plot_selection: true
  ga_population_size: 100
  ga_n_generations: 50
  ga_crossover_prob: 0.7
  ga_mutation_prob: 0.3

# Model configuration
model:
  model_type: xgb
  tune_hyperparams: true
  test_size: 0.25
  random_state: 42
  xgb_n_estimators: 300
  xgb_learning_rate: 0.05
  xgb_max_depth: 5
  xgb_subsample: 0.7
  xgb_colsample_bytree: 0.7

# Output configuration
output_dir: models
results_dir: results
verbose: true

# MLflow configuration
mlflow:
  enabled: true
  experiment_name: nirs-tomato-brix-genetic-algorithm 