name: Auto-format

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    
    - name: Auto-format with Ruff
      run: |
        # Run Ruff linter with auto-fix
        ruff check --fix .
        
        # Format code with Ruff
        ruff format .
        
        # If there are changes, commit them
        if [[ -n $(git status --porcelain) ]]; then
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Apply automatic code formatting with Ruff"
          git push
        else
          echo "No changes to commit."
        fi 