name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Lint with flake8
      run: |
        flake8 nirs_tomato tests
    
    - name: Check formatting with black
      run: |
        black --check nirs_tomato tests
    
    - name: Check imports with isort
      run: |
        isort --check nirs_tomato tests
    
    - name: Type check with mypy
      run: |
        mypy nirs_tomato 